// <auto-generated />
namespace LesioBlog2_Repo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userMess_removed_UserPK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userMess_removed_UserPK));
        
        string IMigrationMetadata.Id
        {
            get { return "202001031239188_userMess_removed_UserPK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
