// <auto-generated />
namespace LesioBlog2_Repo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserMessFix2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserMessFix2));
        
        string IMigrationMetadata.Id
        {
            get { return "202001031229427_UserMessFix2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
